name: Test Workflow

on:
  push:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - run: echo "Workflow is working!"
